name: Deploy Flutter Web (gh-pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Enable web
        run: flutter config --enable-web
      - name: Cache pub deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Flutter doctor
        run: flutter doctor -v
      - name: Fetch dependencies
        run: flutter pub get
      - name: Build web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"
      - name: List build output
        run: ls -R build/web | head -n 100 || find build/web -maxdepth 2 -type f | head -n 100
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
          commit_message: "deploy: ${{ github.sha }}"
